n0 = int(input('digite o numero para ver a tabuada ele:'))

print('-'*12)
print('1 x {} = {}'.format(n0 , n0*1))
print('2 x {} = {}'.format(n0 , n0*2))
print('3 x {} = {}'.format(n0 , n0*3))
print('4 x {} = {}'.format(n0 , n0*4))
print('5 x {} = {}'.format(n0 , n0*5))
print('6 x {} = {}'.format(n0 , n0*6))
print('7 x {} = {}'.format(n0 , n0*7))
print('8 x {} = {}'.format(n0 , n0*8))
print('9 x {} = {}'.format(n0 , n0*9))
print('10 x {} = {}'.format(n0 , n0*10))
print('-'*12)